
name:  rclnodejs - Linux Build and Test

on:
  push:
    branches:
      - develop
      - jazzy
      - iron-irwini
      - humble-hawksbill
  pull_request:
    branches:
      - develop
      - jazzy
      - iron-irwini
      - humble-hawksbill
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  identify-ros-distro:
    uses: ./.github/workflows/identify-ros-distro.yml

  build:
    needs: identify-ros-distro
    runs-on: ${{ needs.identify-ros-distro.outputs.linuxos }}
    container:
      image: osrf/ros:${{ needs.identify-ros-distro.outputs.distro }}-desktop
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.X, 22.X]
    steps:
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup ROS2
      uses: ros-tooling/setup-ros@v0.7

    - name: Install test-msgs on Linux
      run: |
        sudo apt install ros-${{ needs.identify-ros-distro.outputs.distro }}-test-msgs

    - uses: actions/checkout@v4

    - name: Build and test rclnodejs
      run: |
        source /opt/ros/${{ needs.identify-ros-distro.outputs.distro }}/setup.bash
        npm i
        npm test
