name:  rclnodejs - Linux Build & Compatibility Test

on:
  workflow_dispatch:

jobs:
  build-humble-and-rolling: # iron, humble and rolling distros
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.X, 22.X]
        ros_distribution:
          - jazzy
          - iron
          - humble
          - rolling

    steps:
    - name: Setup ROS2
      uses: ros-tooling/setup-ros@0.7.8
      with:
        required-ros-distributions: ${{ matrix.ros_distribution }}

    - name: Install test-msgs on Linux
      run: |
        sudo apt install ros-${{ matrix.ros_distribution }}-test-msgs
    - uses: actions/checkout@v4.1.7

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build and test rclnodejs
      run: |
        source /opt/ros/${{ matrix.ros_distribution }}/setup.bash
        npm i
        npm test
